Added support for all mobs through Minecraft 1.21.11 (#139)
* Delete addons/mobs/src/main/resources/icons/trader_llama.png:Zone.Identifier

error: invalid path 'addons/mobs/src/main/resources/icons/trader_llama.png:Zone.Identifier'

* Added support for more mobs

* Added missing passive/neutral mobs to `allowed-mobs`

* Added missing passive mob `bat` to `allowed-mobs`

* Added `README.md` for mobs addon

* Fixed exception warning logging using wrong addon name

* Fixed using wrong quotes for describing wildcard usage in README for `allowed-mobs`

* Changed name of `aboveSurface` to `belowSurface`

The actual code checks if the Y location of the mob is lower than the hightest block Y location of the XZ location of the mob. So the function name was not correct.

* Small README change so it actually reflects generated default config

* Added missing mob `creaking`

* Added capital letters to mobs addon `README` headers

* Added missing mobs `camel_husk` & `parched`

* Updated `README` with information about why `zombie_horse` & `zombie_nautilus` are not in the default passive/neutral mobs list

* Removed `camel_husk` from default passive/neutral mobs list, as it becomes passive once their hostile mob rider gets separated from them

* Remove submodule version override

Co-authored-by: Copilot Autofix powered by AI <175728472+Copilot@users.noreply.github.com>

---------

Co-authored-by: Jason Penilla <11360596+jpenilla@users.noreply.github.com>
Co-authored-by: Copilot Autofix powered by AI <175728472+Copilot@users.noreply.github.com>